### ISSUE TITLE
[ Lab-1. Box] kvm으로 ubuntu 설치 후, 하드디스크 부팅 문제

### ISSUE THREAD

**Issue by jaisonoh** [SmartX-Labs/SmartX-mini#10]
kvm으로 vm을 생성하고 ubuntu를 메뉴얼대로 설치했습니다. 재부팅후 하드디스크 부팅으로 진입하는데, **Boot failed**란 에러 메세지가 나오면서 부팅이 되지 않습니다.  **boot from hard disk fail**이란 키워드로 찾아보고 있는데, 하드디스크 부팅이 흔한 사례가 아닌지 아직 정확한 원인을 찾지 못하고 있습니다. 

참고로 kvm을 재부팅할 때 -reboot 옵션으로 실행해서, 새로운 kvm을 실행한 것은 아닙니다. 그리고 qemu-kvm으로 생성한 이미지가 문제있을 것 같아 지우고 다시 해봤는데 해결되지 않았습니다.

또한 추가로 우분투를 설치했는데, 왜 우분투 서버로 부팅되지 않고 설치로 진입하는지 궁금합니다.  

에러메세지
![booting from hard disk](https://cloud.githubusercontent.com/assets/9154262/21712853/471927f4-d43a-11e6-974a-fcd5b9af552b.PNG)

**Comment by TaekhoNam** [comment]
본 이슈는 처음보는 현상이라 답변을 바로 드리기 애매한 상황입니다.
주말에 BoxLab 슬라이드를 따라서 KVM 설치를 진행해 본 뒤 다시 한번 답변을 드리겠습니다.

**Comment by TaekhoNam** [comment]
동일한 환경에서 실험을 해보고자 하는데, 실험 환경에 대해서 답변주시길 희망합니다.

1. 하드웨어 머신이 Intel NUC인가요?
2. 하드웨어 머신에서 베어메탈로 사용하신 OS가 Ubuntu가 맞나요?
3. Ubuntu라면 버전은 무엇인가요?

위 내용에 대해서 답변주시면, 위 이슈를 해결하는데 보다 도움이 될 것 같습니다.

**Comment by jaisonoh** [comment]
우선 답변고맙습니다.
인텔 NUC을 사용했고 Ubuntu 버전은 16.04.1로 ,
이건 랩스에서 권유한 드랍박스 링크의 우분투를 사용했을 때 
vm의 cdrom이 이미지를 인식하지 못해서 문중님이 주신 이미지입니다.

**Comment by TaekhoNam** [comment]
안녕하세요, 답변이 늦었습니다.

우선 위에서 보여주신 이미지는 제가 접근권한이 없어서 볼수가 없네요.
슬라이드에 올려진 이미지 링크는 정상적으로 동작하도록 변경했습니다. 하지만 아마도 이미지의 문제는 아닐 것으로 판단됩니다. 

아쉽게도 아직까지 어떤 문제로 인해서 이런 이슈가 발생했는 지 정확히 파악하지 못했습니다.
이에 동일한 슬라이드 자료를 참고해서 실습을 진행해보니 이상없이 부팅이 완료된 것을 확인했습니다.

실험 역시 Intel NUC과 우분투 14.04 64bit server 이미지를 통해서 진행했습니다.

**Comment by jaisonoh** [comment]
아 아닙니다. 
저도 다시해보고 해결되면 이슈에 올리고 이슈 클로즈 하도록 하겠습니다.

**Comment by jaisonoh** [comment]
우분투 공식 이미지로 하니까 하드디스크 부팅이 해결되었습니다.
