### ISSUE TITLE
Lab간의 연계에 대한 issue

### ISSUE THREAD

**Issue by jckwon** [SmartX-Labs/SmartX-mini#6]
Box Lab - Interconnect Lab - Tower Lab 이 세개의 Lab은
앞 단계의 Lap에서 구축한 환경들을 그대로 활용하여 실습을 해야 합니다.
이러한 내용을 모르고 앞서 실습한 내용들을 모두 정리한다면,
다음 단계의 Lap을 수행하려고 하는 경우 처음부터 다시 진행해야 하는 불편함이 있습니다.

반대로 앞의 실습했던 것들을 정리 해주어야 하는 경우도 있습니다.
Function Lap에서 80번 포트를 사용하여 실습한 뒤 그대로 두고 
이어서 WepApp Lab실습을 진행하는 경우, WepApp Lab에서도 80번 포트를 사용하여 
실습이 진행되는 부분이 있어 충돌이 발생하였습니다.

자료에 이러한 정보에 대해 명시해 주시면 이러한 혼란을 방지하는데
많은 도움이 되겠다는 생각이 들어 제안을 드립니다.

**Comment by smartx-srkim** [comment]
현장에서 해설과 함께 진행할 목적으로 작성된 자료인 까닭에
Lab간의 연계에 관한 내용을 비롯하여 일부 설명이 부족한 점이 있습니다.

포트 충돌 내용을 포함하여 각 Lab별 담당자들이 해당 내용을 보완할 수 있도록 하겠습니다.
